// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240519085943_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("fbf567f0-0a45-49dd-a698-ef917db245a2"),
                            DateTime = new DateTime(2024, 5, 19, 11, 59, 42, 652, DateTimeKind.Local).AddTicks(5311),
                            Description = "Want to learn how to grow your business on Instagram? Join Henry, BT's social media manager to learn how you can skyrocket your business on Instagram From content ideas, to hashtags, to new trends you should look out for, in this Masterclass, Henry will cover what you need to know in order to grow your business organically on Instagram ",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Location = "Online",
                            OrganizerId = new Guid("c807e923-3b29-4f69-961c-b036904e7e6d"),
                            Price = 20m,
                            Title = "Grow Your Small Business On Instagram"
                        },
                        new
                        {
                            EventId = new Guid("694f39d3-7b5f-40cf-b57d-73ff8aa4becf"),
                            DateTime = new DateTime(2024, 5, 21, 11, 59, 42, 652, DateTimeKind.Local).AddTicks(5380),
                            Description = "You have a glorious opportunity to get your message into the world.\r\n\r\nNever before has there been such an exciting time in communication.\r\n\r\nThe ability to transmit your words across the world has existed for decades.\r\n\r\nWhat has changed a result of COVID-19 is now people are LISTENING.\r\n\r\nVirtual communication has now been accepted as the norm.\r\n\r\nPeople know that they need to tune into the Facebook Lives and join the Zoom meetings otherwise they are going to be left out of the loop.\r\n\r\nThey are ready to hear your message.\r\n\r\nAre you ready to give it to them?\r\n\r\nYour phone and your computer are all you need to make a difference in the world.\r\n\r\nYou have a voice, it’s time to use it.\r\n\r\nYou have a story, it’s time to tell it.\r\n\r\nYou have a message, it’s time to share it.\r\n\r\nImagine being able to reach people in places you’ve never heard of and changing the lives of people you have never met.\r\n\r\nThat possibility is more real than ever thanks to virtual speaking.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            Location = "Yuri Gagarin Blvd 2001 Chişinău Moldova",
                            OrganizerId = new Guid("c807e923-3b29-4f69-961c-b036904e7e6d"),
                            Price = 0m,
                            Title = "Virtual Speaking Masterclass"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("b43a0c0d-0c54-4cbb-9a41-2f834c493c26"),
                            EventId = new Guid("fbf567f0-0a45-49dd-a698-ef917db245a2"),
                            Price = 20m,
                            Quantity = 3,
                            Type = "Premium",
                            UserId = new Guid("c807e923-3b29-4f69-961c-b036904e7e6d")
                        },
                        new
                        {
                            TicketId = new Guid("136c240b-6e9a-4803-8033-2b5aba4efd66"),
                            EventId = new Guid("694f39d3-7b5f-40cf-b57d-73ff8aa4becf"),
                            Price = 0m,
                            Quantity = 1,
                            Type = "Regular",
                            UserId = new Guid("c807e923-3b29-4f69-961c-b036904e7e6d")
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntraOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c807e923-3b29-4f69-961c-b036904e7e6d"),
                            Email = "example@gmail.com",
                            EntraOid = new Guid("9c9e35cd-5396-4bd2-be7e-502beb1747d0"),
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Event", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Ticket", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
